name: AutoBuild-Android

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Set up keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > bekeystore.jks
      - name: build
        env:
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
          keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
          keystore_alias: key0
        run: |
          ./gradlew android:assembleRelease
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mindustryA
          path: ./android/build/outputs/apk/release/*.apk
