name: AutoBuild

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger BE build
        run: |
          git clone --depth=1 --branch=master https://github.com/YaeSakuraQvQ/Mindustry-CN-ARC/
          cd Mindustry-CN-ARC
          gradlew desktop:dist
